name: Build & test
on: [push, pull_request]
  # push:
  #   branches:
  #     - 'master' 
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  build:
    name: Build & test all packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.1'
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Compile all packages
        run: make build-local
      - name: Run all unit tests
        run: make test-local