name: Build & test
on: 
  push:
    branches:
      - 'master' 
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build & test all packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.1'
      - name: Switch to temporal branch so we re-attach head
        run: |
          git switch -c temporal-pr-branch
          git status
      - name: Fetch complete history for blame information
        run: |
          git fetch --prune --no-tags --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Install required packages
        run: |
          sudo apt-get install git -y
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      #- name: Compile all packages
      #  run: make build-local
      - name: Add ~/go/bin to PATH
        run: echo "::add-path::~/go/bin"
      - name: Add /usr/local/bin to PATH
        run: echo "::add-path::/usr/local/bin"
      - name: Install tools required for local execution
        run: make install-tools-local
      - name: Setup git username and email
        run: |
          git config --global user.name "John Doe"
          git config --global user.email "john.doe@example.com"
      - name: Run all unit tests
        run: make test-local